framework:
    cache:
        prefix_seed: onepay/cache
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            # Pool pour les soldes Mobile Money (TTL: 5 minutes)
            mobile_money.balance_cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 300
            
            # Pool pour les limites de transaction
            transaction.limits_cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 86400 # 24 heures
            
            # Pool pour les statuts de vérification
            verification.status_cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 3600 # 1 heure

            # Pool pour les sessions API
            api.session_cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 1800 # 30 minutes
