# config/packages/lexik_jwt_authentication.yaml
#lexik_jwt_authentication:
 #   secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Chemin vers la clé privée
  #  public_key: '%kernel.project_dir%/config/jwt/public.pem'  # Chemin vers la clé publique
   # pass_phrase: 'fopoussi' # Remplacez par la passphrase que vous avez définie
    #token_ttl: 3600 # Durée de validité du token en secondes (1 heure par défaut)


lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: false
        query_parameter:
            enabled: false
