parameters:
    transaction.log_file: '%kernel.project_dir%/var/log/transactions.log'

services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Configuration automatique des services

    # Enregistrement des services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventSubscriber\ExceptionSubscriber:
        arguments:
            $erreurLogger: '@monolog.logger.erreur'
            $environment: '%kernel.environment%'

    # Configuration explicite des services
    lexik_jwt_authentication.security.jwt_token_authenticator:
        class: Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JWTAuthenticator
        arguments:
            - '@lexik_jwt_authentication.jwt_manager'
            - '@lexik_jwt_authentication.token_extractor.chain_token_extractor'
            - '@security.user_checker'

    # Configuration explicite du service TransactionLogger
    App\Service\TransactionLogger:
        arguments:
            $logFile: '%transaction.log_file%'

    # Configuration explicite des services
    App\Processor\OnepayTransactionProcessor:
        tags: [api_platform.state_processor]

    App\Controller\OnepayTransactionController:
        tags: [api_platform.controller]

    # Filtres personnalisés
    onepay_transaction.status_filter:
        class: App\Filter\StatusFilter
        tags: ['api_platform.filter']

    onepay_transaction.amount_filter:
        class: App\Filter\AmountFilter
        tags: ['api_platform.filter']

    # Configuration du service JWT Authenticator
    App\Security\OnepayAuthenticator:
        arguments:
            $clientRegistry: '@knpu.oauth2.registry'
            $router: '@router'

   # App\Security\AccessDeniedHandler:
    #    arguments:
     #       $router: '@router'
